#!/bin/bash
set -euxo pipefail

echo "hello, world" >/tmp/hello.txt
openssl enc -aes-256-cbc -pbkdf2 -in /tmp/hello.txt -out /tmp/aes.bin -pass pass:demo
openssl enc -aes-256-cbc -pbkdf2 -in /tmp/aes.bin -pass pass:demo -d
